# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false# Ignora todas as regras de estilo. Apenas verifique se há erros de sintaxe.
Layout/InitialIndentation:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/PercentLiteralDelimitERS:
  Enabled: false

# Adicione esta linha para ignorar arquivos que você não criou
AllCops:
  Exclude:
    - 'lib/tasks/cucumber.rake'
    - 'config/environments/*.rb'
    - 'bin/*'
    - 'db/schema.rb'
